#!/usr/bin/env bash
set -euo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$APP_DIR/.env"
TUNNEL_SERVICE_NAME="ergo-rust-node-tunnel.service"

say() {
  printf '\n=== %s ===\n' "$1"
}

ask_default() {
  local prompt="$1"
  local default="$2"
  local answer
  read -r -p "$prompt [$default]: " answer
  printf '%s\n' "${answer:-$default}"
}

ask_yes_no() {
  local prompt="$1"
  local default="$2"
  local answer suffix
  if [[ "$default" == "y" ]]; then
    suffix="Y/n"
  else
    suffix="y/N"
  fi

  read -r -p "$prompt [$suffix]: " answer
  answer="${answer:-$default}"

  case "$answer" in
    y|Y|yes|YES|Yes) return 0 ;;
    *) return 1 ;;
  esac
}

say "ergo-node-rust micro-display setup"

cat <<'EOF_TEXT'
This setup writes a local .env file used by run_micro_window.sh.

Supported modes:
  1) Rust node API is local on this machine
  2) Rust node API is on another machine, reached through an SSH tunnel
  3) Rust node API is directly reachable by URL

Security note:
  For remote nodes, SSH tunnel mode is recommended. It lets the node API remain
  bound to 127.0.0.1 on the node machine instead of exposing it on the LAN/WAN.
EOF_TEXT

say "Check Python/Tkinter"
if python3 - <<'PY' >/dev/null 2>&1
import tkinter
PY
then
  echo "python3-tk is available."
else
  echo "python3-tk is not available."
  echo "Install it with:"
  echo "  sudo apt update && sudo apt install -y python3-tk"
  exit 1
fi

say "Choose node connection mode"
echo "1) Local API / already-tunneled API at http://127.0.0.1:9052"
echo "2) Remote node via SSH tunnel"
echo "3) Direct API URL"
MODE="$(ask_default "Choose mode" "1")"

NODE_URL="http://127.0.0.1:9052"
UPTIME_SSH_HOST=""
CREATE_TUNNEL="false"
TUNNEL_SSH_HOST=""
TUNNEL_LOCAL_PORT="9052"
TUNNEL_REMOTE_HOST="127.0.0.1"
TUNNEL_REMOTE_PORT="9052"

case "$MODE" in
  1)
    NODE_URL="$(ask_default "Rust node API URL" "http://127.0.0.1:9052")"
    ;;
  2)
    CREATE_TUNNEL="true"
    TUNNEL_SSH_HOST="$(ask_default "SSH host for Rust node machine, e.g. user@host or ssh alias" "my-ergo-node")"
    TUNNEL_LOCAL_PORT="$(ask_default "Local tunnel port" "9052")"
    TUNNEL_REMOTE_HOST="$(ask_default "Remote API bind host" "127.0.0.1")"
    TUNNEL_REMOTE_PORT="$(ask_default "Remote API port" "9052")"
    NODE_URL="http://127.0.0.1:${TUNNEL_LOCAL_PORT}"

    if ask_yes_no "Use the same SSH host for service uptime display?" "n"; then
      UPTIME_SSH_HOST="$TUNNEL_SSH_HOST"
    fi

    if ! ssh -o BatchMode=yes -o ConnectTimeout=5 "$TUNNEL_SSH_HOST" true 2>/dev/null; then
      echo ""
      echo "WARNING: cannot reach $TUNNEL_SSH_HOST non-interactively."
      echo "The systemd unit requires BatchMode=yes SSH (key auth, no password)."
      if ! ask_yes_no "Continue anyway?" "n"; then
        echo "Aborting."
        exit 1
      fi
    else
      echo "SSH host $TUNNEL_SSH_HOST is reachable non-interactively."
    fi
    ;;
  3)
    NODE_URL="$(ask_default "Rust node API URL" "http://127.0.0.1:9052")"
    ;;
  *)
    echo "Invalid mode: $MODE"
    exit 1
    ;;
esac

say "Reference node"
REFERENCE_URL="$(ask_default "Reference Ergo node API URL" "http://159.89.116.15:11088")"
REFERENCE_LABEL_DEFAULT="${REFERENCE_URL#http://}"
REFERENCE_LABEL_DEFAULT="${REFERENCE_LABEL_DEFAULT#https://}"
REFERENCE_LABEL_DEFAULT="${REFERENCE_LABEL_DEFAULT%/}"
REFERENCE_LABEL="$(ask_default "Reference label shown in UI" "$REFERENCE_LABEL_DEFAULT")"

say "Refresh interval"
REFRESH_MS="$(ask_default "Refresh interval in milliseconds" "2000")"

if [[ "$CREATE_TUNNEL" == "false" ]]; then
  if ask_yes_no "Configure optional SSH host for uptime display?" "n"; then
    UPTIME_SSH_HOST="$(ask_default "SSH host for uptime probing" "")"
  fi
fi

say "Write .env"
if [[ -f "$ENV_FILE" ]]; then
  cp "$ENV_FILE" "${ENV_FILE}.bak"
  echo "Backed up existing .env to .env.bak"
fi
cat > "$ENV_FILE" <<EOF_ENV
# ergo-node-rust micro-display config
# Generated by setup_dashboard.sh

ERGO_RUST_NODE_URL=$NODE_URL
ERGO_RUST_REFERENCE_URL=$REFERENCE_URL
ERGO_RUST_REFERENCE_LABEL=$REFERENCE_LABEL
ERGO_RUST_REFRESH_MS=$REFRESH_MS
ERGO_RUST_UPTIME_SSH_HOST=$UPTIME_SSH_HOST
EOF_ENV

chmod 600 "$ENV_FILE"
echo "Wrote: $ENV_FILE"

if [[ "$CREATE_TUNNEL" == "true" ]]; then
  say "Create user-level SSH tunnel service"

  USER_SYSTEMD_DIR="$HOME/.config/systemd/user"
  mkdir -p "$USER_SYSTEMD_DIR"

  cat > "$USER_SYSTEMD_DIR/$TUNNEL_SERVICE_NAME" <<EOF_SERVICE
[Unit]
Description=SSH tunnel to ergo-node-rust API
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/bin/ssh -N -T \\
  -o ExitOnForwardFailure=yes \\
  -o ServerAliveInterval=30 \\
  -o ServerAliveCountMax=3 \\
  -L 127.0.0.1:${TUNNEL_LOCAL_PORT}:${TUNNEL_REMOTE_HOST}:${TUNNEL_REMOTE_PORT} \\
  ${TUNNEL_SSH_HOST}
Restart=always
RestartSec=5

[Install]
WantedBy=default.target
EOF_SERVICE

  systemctl --user daemon-reload
  systemctl --user enable --now "$TUNNEL_SERVICE_NAME"

  echo "Created and started user service: $TUNNEL_SERVICE_NAME"
  echo "Check with:"
  echo "  systemctl --user status $TUNNEL_SERVICE_NAME"
fi

say "Optional: .desktop launcher"
if ask_yes_no "Create a .desktop launcher in ~/.local/share/applications?" "n"; then
  DESKTOP_DIR="$HOME/.local/share/applications"
  DESKTOP_FILE="$DESKTOP_DIR/ergo-rust-sync-dashboard.desktop"
  mkdir -p "$DESKTOP_DIR"
  cat > "$DESKTOP_FILE" <<EOF_DESKTOP
[Desktop Entry]
Type=Application
Name=Ergo Rust Sync Dashboard
Comment=Native sync monitor for ergo-node-rust
Exec=$APP_DIR/run_micro_window.sh
Icon=utilities-system-monitor
Terminal=false
Categories=Utility;Network;Monitor;
EOF_DESKTOP
  chmod 644 "$DESKTOP_FILE"
  echo "Created: $DESKTOP_FILE"
fi

say "Test configured Rust node API"
if curl -fsS --max-time 5 "$NODE_URL/info" >/dev/null; then
  echo "Rust node API OK: $NODE_URL/info"
else
  echo "WARNING: Could not reach Rust node API at $NODE_URL/info"
  echo "The display can still start, but it will show STALE until the API is reachable."
fi

say "Done"
echo "Start the micro-display with:"
echo "  $APP_DIR/run_micro_window.sh"
